"""
Module: data_generator
Description: Single point of generation of synthetic, reproducible instances for every
             WSRP model. Each call builds the full instance (graph, time parameters,
             time windows) and every model reads only the keys it needs.
             Each feature draws from its own random stream derived from the seed, so
             adding a feature never changes the data generated by the previous ones.
"""

import math
import numpy as np
from typing import Any

# Random stream of each feature. The graph uses the plain seed; every other feature
# uses default_rng([random_seed, stream]), so its draws never shift the graph's.
TIME_WINDOWS_STREAM = 1
ASSIGNMENTS_STREAM = 2


def generate_wsrp_instance(num_properties: int = 5, random_seed: int = 42, num_brokers: int = 1,
                           travel_time: int = 30, service_time: int = 60, horizon: int = 600,
                           fixed_ratio: float = 0.2, window_width: tuple[int, int] = (120, 360),
                           assigned_ratio: float = 0.4) -> dict[str, Any]:
    """
    Generates a synthetic WSRP instance with the data of every model.

    Args:
        num_properties (int): The number of properties to be visited.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        num_brokers (int): Number of brokers |K|. The hidden schedule behind the time windows
            is split among them, so with more than one broker the visits may overlap.
        travel_time (int): Constant travel time T between any two nodes, in minutes.
        service_time (int): Constant visit duration S, in minutes.
        horizon (int): Target length of the working day over which the visits are spread, in
            minutes (e.g. 600 = 08:00 to 18:00). Extended when the visits don't fit in it.
        fixed_ratio (float): Share of the properties with a fixed start time.
        window_width (tuple[int, int]): Min and max width of a flexible time window, in minutes.
        assigned_ratio (float): Share of the properties whose visit already has a broker.

    Returns:
        dict[str, Any]: The instance payload. Keys and the models that read them:
            - 'num_nodes', 'coordinates', 'distance_matrix': all models.
            - 'travel_time', 'service_time': M1 onwards.
            - 'earliest_start', 'latest_start', 'fixed_visits': M1 onwards.
            - 'num_brokers': M2 onwards.
            - 'assigned_broker': M3 onwards.
    """
    num_nodes = num_properties + 1

    data_payload = _generate_graph(num_nodes, random_seed)
    data_payload['num_brokers'] = num_brokers
    data_payload['travel_time'] = travel_time
    data_payload['service_time'] = service_time

    time_windows = _generate_time_windows(num_nodes, random_seed, num_brokers, travel_time, service_time,
                                          horizon, fixed_ratio, window_width)
    reference_broker = time_windows.pop('reference_broker')
    data_payload.update(time_windows)
    data_payload['assigned_broker'] = _generate_assignments(num_nodes, random_seed, reference_broker,
                                                            assigned_ratio)

    return data_payload


def _generate_graph(num_nodes: int, random_seed: int) -> dict[str, Any]:
    """
    Distributes the nodes in a 100x100 grid map and computes the Euclidean distance matrix.

    Args:
        num_nodes (int): Total number of nodes |V|. Index 0 is the depot.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.

    Returns:
        dict[str, Any]: The number of nodes, coordinates, and the computed distance matrix.
    """
    # 1. Enforcing Reproducibility
    rng = np.random.default_rng(random_seed)

    # 2. Spatial Distribution
    # Generating random (x, y) coordinates in a 100x100 grid map
    # Index 0 will always represent the Depot (Real Estate Agency)
    coordinates = rng.random((num_nodes, 2)) * 100.0

    # 3. Distance Matrix Computation
    # Creating an N x N matrix initialized with zeros
    distance_matrix = np.zeros((num_nodes, num_nodes))

    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:
                # Calculating Euclidean distance between node i and node j
                dist = math.hypot(coordinates[i][0] - coordinates[j][0],
                                  coordinates[i][1] - coordinates[j][1])
                # Rounding to 2 decimal places to avoid floating-point representation issues
                distance_matrix[i][j] = round(dist, 2)

    return {
        'num_nodes': num_nodes,
        'coordinates': coordinates.tolist(),
        'distance_matrix': distance_matrix.tolist()
    }


def _generate_time_windows(num_nodes: int, random_seed: int, num_brokers: int, travel_time: int,
                           service_time: int, horizon: int, fixed_ratio: float,
                           window_width: tuple[int, int]) -> dict[str, Any]:
    """
    Builds the time windows around a hidden reference schedule, which guarantees the
    instance is feasible. A share of the visits gets a fixed start time (e_i = l_i),
    emulating visits already scheduled by the visitors.

    Args:
        num_nodes (int): Total number of nodes |V|. Index 0 is the depot.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        num_brokers (int): Number of brokers sharing the hidden schedule.
        travel_time (int): Constant travel time T between any two nodes, in minutes.
        service_time (int): Constant visit duration S, in minutes.
        horizon (int): Target length of the working day, in minutes.
        fixed_ratio (float): Share of the properties with a fixed start time.
        window_width (tuple[int, int]): Min and max width of a flexible time window, in minutes.

    Returns:
        dict[str, Any]: The time windows (e_i, l_i) for every node, the fixed visits, and the
            broker who does each visit in the hidden schedule (0 for the depot).
    """
    num_properties = num_nodes - 1

    # 1. Enforcing Reproducibility
    rng = np.random.default_rng([random_seed, TIME_WINDOWS_STREAM])

    # 2. Hidden Reference Schedule
    # A random visiting order split among the brokers in consecutive shares
    reference_order = rng.permutation(np.arange(1, num_nodes))
    broker_shares = np.array_split(reference_order, num_brokers)

    # The day is a target, not a constraint: the models before Case 8 have no working-day
    # limit, so a day too short for the busiest broker's work is extended to fit it
    horizon = max(horizon, max(len(share) for share in broker_shares) * (travel_time + service_time))

    # Each broker's slack in the day is spread as idle gaps between its visits
    reference_start = [0] * num_nodes
    reference_broker = [0] * num_nodes
    for broker, share in enumerate(broker_shares, start=1):
        slack = horizon - len(share) * (travel_time + service_time)
        gaps = rng.random(len(share) + 1)
        idle_before = np.cumsum(gaps / gaps.sum() * slack)[:len(share)]

        for position, node in enumerate(share):
            reference_start[node] = math.floor(travel_time + position * (travel_time + service_time)
                                               + idle_before[position])
            reference_broker[node] = broker

    # 3. Time Windows
    # The depot (node 0) may be left at any time of the day
    earliest_start = [0] * num_nodes
    latest_start = [horizon] * num_nodes

    num_fixed = round(fixed_ratio * num_properties)
    fixed_visits = sorted(int(node) for node in rng.choice(np.arange(1, num_nodes), size=num_fixed, replace=False))

    for node in range(1, num_nodes):
        if node in fixed_visits:
            # Visit already scheduled by the visitor: e_i = l_i
            earliest_start[node] = reference_start[node]
            latest_start[node] = reference_start[node]
        else:
            # Flexible visit: a window containing the reference start time
            width = int(rng.integers(window_width[0], window_width[1] + 1))
            opening = reference_start[node] - int(rng.integers(0, width + 1))
            earliest_start[node] = max(0, opening)
            latest_start[node] = min(horizon - service_time, opening + width)

    return {
        'earliest_start': earliest_start,
        'latest_start': latest_start,
        'fixed_visits': fixed_visits,
        'reference_broker': reference_broker
    }


def _generate_assignments(num_nodes: int, random_seed: int, reference_broker: list[int],
                          assigned_ratio: float) -> list[int]:
    """
    Picks the visits that already have a broker, emulating visits booked with a specific
    broker. Each one goes to the broker who does it in the hidden schedule, which keeps
    the instance feasible.

    Args:
        num_nodes (int): Total number of nodes |V|. Index 0 is the depot.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        reference_broker (list[int]): Broker of each visit in the hidden schedule.
        assigned_ratio (float): Share of the properties whose visit already has a broker.

    Returns:
        list[int]: The broker assigned to each node, 0 when any broker may do it.
    """
    rng = np.random.default_rng([random_seed, ASSIGNMENTS_STREAM])

    num_assigned = round(assigned_ratio * (num_nodes - 1))
    assigned_visits = rng.choice(np.arange(1, num_nodes), size=num_assigned, replace=False)

    assigned_broker = [0] * num_nodes
    for node in assigned_visits:
        assigned_broker[node] = reference_broker[node]

    return assigned_broker


if __name__ == "__main__":
    # Quick sanity check for the terminal
    mock_data = generate_wsrp_instance(num_properties=5)
    print("--- Instance Generation Successful ---")
    print(f"Total Nodes (Depot + Properties): {mock_data['num_nodes']}")
    print("Distance Matrix (0 to 2):")
    for row in mock_data['distance_matrix'][:3]:
        print(row)
    print("Time Windows [e_i, l_i]:")
    for node in range(mock_data['num_nodes']):
        print(f"Node {node}: [{mock_data['earliest_start'][node]}, {mock_data['latest_start'][node]}]")
