"""
Module: data_generator
Description: Single point of generation of synthetic, reproducible instances for every
             WSRP model. Each call builds the full instance (graph, time parameters,
             time windows) and every model reads only the keys it needs.
             Each feature draws from its own random stream derived from the seed, so
             adding a feature never changes the data generated by the previous ones.
"""

import math
import numpy as np
from typing import Any, Optional, Union

# Random stream of each feature. The graph uses the plain seed; every other feature
# uses default_rng([random_seed, stream]), so its draws never shift the graph's.
TIME_WINDOWS_STREAM = 1
ASSIGNMENTS_STREAM = 2
SERVICE_TIMES_STREAM = 3
HOMES_STREAM = 4
LUNCH_SPOTS_STREAM = 5
SHIFTS_STREAM = 6
FLEET_STREAM = 7

# num_brokers value that draws the fleet from the instance instead of fixing it
AUTO_BROKERS = "auto"

# Most routing arcs (brokers x arcs between the nodes) an automatic fleet may give the solver.
# The bound is memory, not time: 225 properties with 44 brokers, about 2.24 million arcs,
# solved without running out of memory. A constant, not the free memory, keeps a seed's
# fleet the same on every machine.
MAX_ROUTING_ARCS = 2_250_000

# Range of the start and of the end of each broker's shifts, in minutes from 08:00
MORNING_SHIFT = ((0, 60), (210, 270))           # Starts 08:00 to 09:00, ends 11:30 to 12:30
AFTERNOON_SHIFT = ((300, 360), (540, 600))      # Starts 13:00 to 14:00, ends 17:00 to 18:00


def generate_wsrp_instance(num_properties: int = 5, random_seed: int = 42, num_brokers: Union[int, str] = 1,
                           travel_time: int = 30, service_time: int = 60, horizon: int = 600,
                           fixed_ratio: float = 0.2, window_width: tuple[int, int] = (120, 360),
                           assigned_ratio: float = 0.4, service_time_variation: int = 0,
                           speed_profile: Optional[list[tuple[int, float]]] = None,
                           working_hours: tuple[int, int] = (0, 540),
                           start_at_homes: bool = False, days_off: int = 0,
                           split_shifts: bool = False,
                           lunch_break: Optional[tuple[int, int, int]] = None,
                           max_day_length: Optional[int] = None,
                           graph: Optional[dict[str, Any]] = None,
                           max_routing_arcs: int = MAX_ROUTING_ARCS) -> dict[str, Any]:
    """
    Generates a synthetic WSRP instance with the data of every model.

    Args:
        num_properties (int): The number of properties to be visited.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        num_brokers (Union[int, str]): Number of brokers |K|. The hidden schedule behind the time
            windows is split among them, so with more than one broker the visits may overlap.
            AUTO_BROKERS draws it at random between the fewest brokers the visits need and the
            most the solver can take: see _auto_fleet_instance.
        travel_time (int): Constant travel time T between any two nodes, in minutes.
        service_time (int): Constant visit duration S, in minutes.
        horizon (int): Target length of the working day over which the visits are spread, in
            minutes (e.g. 600 = 08:00 to 18:00). Extended when the visits don't fit in it.
        fixed_ratio (float): Share of the properties with a fixed start time.
        window_width (tuple[int, int]): Min and max width of a flexible time window, in minutes.
        assigned_ratio (float): Share of the properties whose visit already has a broker.
        service_time_variation (int): Each visit lasts a duration drawn from
            [S - variation, S + variation], in minutes. With 0, every visit lasts S.
        speed_profile (Optional[list[tuple[int, float]]]): Periods of the day as (start minute,
            speed in distance units per minute), the first starting at 0. The travel time of a
            trip depends on the period it leaves in. With None, every trip takes T.
        working_hours (tuple[int, int]): Start and regular end of every broker's working day,
            in minutes (e.g. (0, 540) = 08:00 to 17:00).
        start_at_homes (bool): Whether each broker of the hidden schedule leaves his own home
            instead of the agency, for the models where the brokers start the day at home.
        days_off (int): Number of brokers who have no shifts in the day.
        split_shifts (bool): Whether the hidden schedule fits each broker's visits in his own
            morning shift, from his home, and afternoon shift, from his lunch spot, for the
            models where the visits never go past the end of a shift.
        lunch_break (Optional[tuple[int, int, int]]): Earliest start, latest start and duration
            of the lunch break the hidden schedule leaves in each broker's day, in minutes, for
            the models where every broker must break for lunch. Not used with split_shifts.
        max_day_length (Optional[int]): Longest day a broker of the hidden schedule may work, in
            minutes, for the models that limit it. Not used with split_shifts.
        graph (Optional[dict[str, Any]]): Nodes to visit instead of the random 100x100 map, with
            'num_nodes' (num_properties + 1), 'coordinates' and 'distance_matrix', e.g. real
            listings. Every other feature is still generated.
        max_routing_arcs (int): Most brokers x arcs between the nodes an AUTO_BROKERS fleet may
            give the solver. Not used with a fixed num_brokers.

    Returns:
        dict[str, Any]: The instance payload. Keys and the models that read them:
            - 'num_nodes', 'coordinates', 'distance_matrix': all models.
            - 'travel_time': M1 to M4.
            - 'service_time': M1 to M3.
            - 'earliest_start', 'latest_start', 'fixed_visits': M1 onwards.
            - 'num_brokers': M2 onwards.
            - 'assigned_broker': M3 onwards.
            - 'service_times': M4 onwards.
            - 'period_starts', 'travel_times': M5 onwards.
            - 'home_coordinates', 'home_distances', 'home_travel_times': M7 onwards.
            - 'shift_start', 'shift_end': M7.
            - 'lunch_spot_coordinates', 'lunch_spot_distances', 'lunch_spot_travel_times', 'shifts': M8.
            - 'schedule_brokers', 'max_brokers': with AUTO_BROKERS, the range num_brokers was
              drawn from.

    Raises:
        ValueError: If the visits don't fit in the shifts, or in the longest working day, or
            the graph does not have num_properties + 1 nodes.
    """
    if num_brokers == AUTO_BROKERS:
        return _auto_fleet_instance(num_properties, random_seed, max_routing_arcs, {
            'travel_time': travel_time, 'service_time': service_time, 'horizon': horizon,
            'fixed_ratio': fixed_ratio, 'window_width': window_width, 'assigned_ratio': assigned_ratio,
            'service_time_variation': service_time_variation, 'speed_profile': speed_profile,
            'working_hours': working_hours, 'start_at_homes': start_at_homes, 'days_off': days_off,
            'split_shifts': split_shifts, 'lunch_break': lunch_break, 'max_day_length': max_day_length,
            'graph': graph,
        })

    num_nodes = num_properties + 1

    if graph is None:
        data_payload = _generate_graph(num_nodes, random_seed)
    elif graph['num_nodes'] != num_nodes:
        raise ValueError(f"The graph has {graph['num_nodes']} nodes, not {num_nodes}.")
    else:
        data_payload = dict(graph)
    data_payload['num_brokers'] = num_brokers
    data_payload['travel_time'] = travel_time
    data_payload['service_time'] = service_time
    data_payload['service_times'] = _generate_service_times(num_nodes, random_seed, service_time,
                                                            service_time_variation)
    data_payload.update(_generate_travel_times(data_payload['distance_matrix'], travel_time, speed_profile))
    for prefix, stream in (('home', HOMES_STREAM), ('lunch_spot', LUNCH_SPOTS_STREAM)):
        places = _generate_broker_places(random_seed, stream, num_brokers, data_payload['coordinates'],
                                         travel_time, speed_profile)
        data_payload.update({f'{prefix}_{key}': value for key, value in places.items()})
    data_payload['shifts'] = _generate_shifts(random_seed, num_brokers, days_off)

    # The hidden schedule assumes the slowest period on every trip, so it stays feasible
    # whichever period each trip actually leaves in
    leg_times = np.max(data_payload['travel_times'], axis=0).tolist()
    if start_at_homes or split_shifts:
        first_legs = np.max(data_payload['home_travel_times'], axis=0).tolist()
    else:
        first_legs = [leg_times[0]] * num_brokers
    lunch_legs = np.max(data_payload['lunch_spot_travel_times'], axis=0).tolist()

    time_windows = _generate_time_windows(num_nodes, random_seed, num_brokers, leg_times, first_legs,
                                          data_payload['service_times'], horizon, fixed_ratio, window_width,
                                          data_payload['shifts'] if split_shifts else None, lunch_legs,
                                          lunch_break, max_day_length)
    reference_broker = time_windows.pop('reference_broker')
    data_payload.update(time_windows)
    data_payload['assigned_broker'] = _generate_assignments(num_nodes, random_seed, reference_broker,
                                                            assigned_ratio)
    data_payload['shift_start'] = [working_hours[0]] * num_brokers
    data_payload['shift_end'] = [working_hours[1]] * num_brokers

    return data_payload


def _auto_fleet_instance(num_properties: int, random_seed: int, max_routing_arcs: int,
                         settings: dict[str, Any]) -> dict[str, Any]:
    """
    Builds the instance with a fleet drawn at random, from the fewest brokers the visits
    need to the most the solver can take.

    The fewest brokers is the smallest count whose hidden schedule fits the day: the visits
    fit in the shifts, and the day is no longer than the model's limit (M7's 12 hours) or,
    without one, the horizon. That schedule is a plan those brokers can carry out, so the instance is feasible
    with them. Every model lets a broker stay at home, so it stays feasible with any larger
    fleet; the solver may need fewer.

    The most is max_fleet. The fleet is drawn uniformly between the two from FLEET_STREAM.
    The brokers beyond the schedule's have their own homes, lunch spots and shifts; the
    schedule's brokers keep exactly the ones they have with a fixed fleet of that size.

    Args:
        num_properties (int): The number of properties to be visited.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        max_routing_arcs (int): Most brokers x arcs between the nodes the fleet may give the solver.
        settings (dict[str, Any]): Every other argument of generate_wsrp_instance.

    Returns:
        dict[str, Any]: The instance payload, with 'schedule_brokers' and 'max_brokers'.

    Raises:
        ValueError: If the visits don't fit in a day even with one broker per property.
    """
    days_off = settings['days_off']
    schedule = None
    for brokers in range(days_off + 1, days_off + num_properties + 1):
        try:
            candidate = generate_wsrp_instance(num_properties=num_properties, random_seed=random_seed,
                                               num_brokers=brokers, **settings)
        except ValueError:
            continue
        if settings['split_shifts'] or candidate['latest_start'][0] <= _day_length(settings):
            schedule = candidate
            break
    if schedule is None:
        raise ValueError("The visits don't fit in a day even with one broker per property; use fewer properties.")

    schedule_brokers = schedule['num_brokers']
    max_brokers = max_fleet(num_properties, schedule_brokers, days_off, max_routing_arcs)
    rng = np.random.default_rng([random_seed, FLEET_STREAM])
    num_brokers = int(rng.integers(schedule_brokers, max_brokers + 1))

    data_payload = dict(schedule)
    data_payload['num_brokers'] = num_brokers
    data_payload['schedule_brokers'] = schedule_brokers
    data_payload['max_brokers'] = max_brokers
    if num_brokers > schedule_brokers:
        # Places are drawn one broker after another, so the first ones are the schedule's
        for prefix, stream in (('home', HOMES_STREAM), ('lunch_spot', LUNCH_SPOTS_STREAM)):
            places = _generate_broker_places(random_seed, stream, num_brokers, data_payload['coordinates'],
                                             settings['travel_time'], settings['speed_profile'])
            data_payload.update({f'{prefix}_{key}': value for key, value in places.items()})
        # The extra brokers all work; the schedule's keep their shifts and days off
        extra_shifts = _generate_shifts(random_seed, num_brokers, 0)[schedule_brokers:]
        data_payload['shifts'] = schedule['shifts'] + extra_shifts
        data_payload['shift_start'] = [settings['working_hours'][0]] * num_brokers
        data_payload['shift_end'] = [settings['working_hours'][1]] * num_brokers
    return data_payload


def max_fleet(num_properties: int, schedule_brokers: int, days_off: int = 0,
              max_routing_arcs: int = MAX_ROUTING_ARCS) -> int:
    """
    Most brokers an automatic fleet may have.

    The solver's routing variables grow with the brokers times the arcs between the nodes,
    so the fleet keeps that product within max_routing_arcs, and never has more working
    brokers than properties. It is never below schedule_brokers, which the instance needs.

    Args:
        num_properties (int): The number of properties to be visited.
        schedule_brokers (int): Fewest brokers the instance needs.
        days_off (int): Number of brokers who have no shifts in the day.
        max_routing_arcs (int): Most brokers x arcs between the nodes the solver may receive.

    Returns:
        int: The largest fleet the draw may pick.
    """
    num_nodes = num_properties + 1
    within_budget = max_routing_arcs // (num_nodes * (num_nodes - 1))
    return max(schedule_brokers, min(num_properties + days_off, within_budget))


def _day_length(settings: dict[str, Any]) -> int:
    """
    Longest day the hidden schedule may take, in minutes: the model's own limit when it has
    one (M7's 12 hours), otherwise the horizon, which the models without a limit only target.
    """
    if settings['max_day_length'] is None:
        return settings['horizon']
    return settings['max_day_length']


def _generate_graph(num_nodes: int, random_seed: int) -> dict[str, Any]:
    """
    Distributes the nodes in a 100x100 grid map and computes the Euclidean distance matrix.

    Args:
        num_nodes (int): Total number of nodes |V|. Index 0 is the depot.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.

    Returns:
        dict[str, Any]: The number of nodes, coordinates, and the computed distance matrix.
    """
    # 1. Enforcing Reproducibility
    rng = np.random.default_rng(random_seed)

    # 2. Spatial Distribution
    # Generating random (x, y) coordinates in a 100x100 grid map
    # Index 0 will always represent the Depot (Real Estate Agency)
    coordinates = rng.random((num_nodes, 2)) * 100.0

    # 3. Distance Matrix Computation
    # Creating an N x N matrix initialized with zeros
    distance_matrix = np.zeros((num_nodes, num_nodes))

    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:
                # Calculating Euclidean distance between node i and node j
                dist = math.hypot(coordinates[i][0] - coordinates[j][0],
                                  coordinates[i][1] - coordinates[j][1])
                # Rounding to 2 decimal places to avoid floating-point representation issues
                distance_matrix[i][j] = round(dist, 2)

    return {
        'num_nodes': num_nodes,
        'coordinates': coordinates.tolist(),
        'distance_matrix': distance_matrix.tolist()
    }


def _generate_service_times(num_nodes: int, random_seed: int, service_time: int,
                            service_time_variation: int) -> list[int]:
    """
    Draws the duration of every visit around the constant visit duration S.

    Args:
        num_nodes (int): Total number of nodes |V|. Index 0 is the depot.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        service_time (int): Mean visit duration S, in minutes.
        service_time_variation (int): Max distance of a duration from S, in minutes.

    Returns:
        list[int]: The duration s_i of the visit at each node, with s_0 = 0 at the depot.
    """
    rng = np.random.default_rng([random_seed, SERVICE_TIMES_STREAM])

    durations = rng.integers(service_time - service_time_variation, service_time + service_time_variation + 1,
                             size=num_nodes - 1)

    return [0] + [int(duration) for duration in durations]


def _generate_travel_times(distance_matrix: list[list[float]], travel_time: int,
                           speed_profile: Optional[list[tuple[int, float]]]) -> dict[str, Any]:
    """
    Computes the travel time of every trip in every period of the day.

    Args:
        distance_matrix (list[list[float]]): Distance c_ij between every pair of nodes.
        travel_time (int): Constant travel time T, used when there is no speed profile.
        speed_profile (Optional[list[tuple[int, float]]]): Periods of the day as (start minute,
            speed in distance units per minute), the first starting at 0.

    Returns:
        dict[str, Any]: The start minute of each period and, for each period, the matrix of
            travel times t_ij in whole minutes (rounded up) of a trip leaving in it.
    """
    num_nodes = len(distance_matrix)

    if speed_profile is None:
        return {
            'period_starts': [0],
            'travel_times': [[[0 if i == j else travel_time for j in range(num_nodes)] for i in range(num_nodes)]]
        }

    return {
        'period_starts': [start for start, _ in speed_profile],
        'travel_times': [[[math.ceil(distance / speed) for distance in row] for row in distance_matrix]
                         for _, speed in speed_profile]
    }


def _generate_broker_places(random_seed: int, stream: int, num_brokers: int, coordinates: list[list[float]],
                            travel_time: int, speed_profile: Optional[list[tuple[int, float]]]) -> dict[str, Any]:
    """
    Places one point per broker (e.g. his home) in the same 100x100 grid map as the nodes,
    and computes the distance and travel times from it to every node.

    Args:
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        stream (int): Random stream of the kind of place.
        num_brokers (int): Number of brokers |K|.
        coordinates (list[list[float]]): (x, y) of every node.
        travel_time (int): Constant travel time T, used when there is no speed profile.
        speed_profile (Optional[list[tuple[int, float]]]): Periods of the day as (start minute,
            speed in distance units per minute), the first starting at 0.

    Returns:
        dict[str, Any]: The coordinates of each broker's place, the distance from it to each
            node and, for each period, the travel time in whole minutes (rounded up) of that trip.
    """
    rng = np.random.default_rng([random_seed, stream])
    place_coordinates = rng.random((num_brokers, 2)) * 100.0

    distances = [[round(math.hypot(place[0] - node[0], place[1] - node[1]), 2) for node in coordinates]
                 for place in place_coordinates]

    if speed_profile is None:
        travel_times = [[[travel_time for _ in row] for row in distances]]
    else:
        travel_times = [[[math.ceil(distance / speed) for distance in row] for row in distances]
                        for _, speed in speed_profile]

    return {
        'coordinates': place_coordinates.tolist(),
        'distances': distances,
        'travel_times': travel_times
    }


def _generate_shifts(random_seed: int, num_brokers: int, days_off: int) -> list[list[tuple[int, int]]]:
    """
    Draws each broker's own shifts: a morning one around 08:00 to 12:00 and an afternoon
    one around 13:00 to 18:00, the gap between them being his lunch break. Some brokers
    may have the day off.

    Args:
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        num_brokers (int): Number of brokers |K|.
        days_off (int): Number of brokers who don't work in the day.

    Returns:
        list[list[tuple[int, int]]]: The (start, end) of the morning and the afternoon shift
            of each broker, in minutes, or no shift for the brokers off.
    """
    rng = np.random.default_rng([random_seed, SHIFTS_STREAM])

    def draw(bounds):
        return int(rng.integers(bounds[0], bounds[1] + 1))

    shifts = [[(draw(start), draw(end)) for start, end in (MORNING_SHIFT, AFTERNOON_SHIFT)]
              for _ in range(num_brokers)]

    for broker in rng.choice(num_brokers, size=days_off, replace=False):
        shifts[broker] = []

    return shifts


def _workload(visits: list[int], first_leg: list[int], leg_times: list[list[int]], service_times: list[int]) -> int:
    """
    Minutes of travel and visits it takes to do the visits in order, from a first trip
    with the given travel times to each node.
    """
    return sum((first_leg[node] if previous is None else leg_times[previous][node]) + service_times[node]
               for previous, node in zip([None, *visits[:-1]], visits))


def _place_visits(rng: np.random.Generator, visits: list[int], first_leg: list[int], leg_times: list[list[int]],
                  service_times: list[int], day_start: int, day_end: int, reference_start: list[int]) -> None:
    """
    Places the visits in order between day_start and day_end, spreading the slack as
    random idle gaps between them, and writes their start times to reference_start.
    """
    slack = day_end - day_start - _workload(visits, first_leg, leg_times, service_times)
    gaps = rng.random(len(visits) + 1)
    idle_before = np.cumsum(gaps / gaps.sum() * slack)[:len(visits)]

    # Minutes of travel and visits done so far, idle gaps aside
    busy = 0
    previous = None
    for position, node in enumerate(visits):
        busy += first_leg[node] if previous is None else leg_times[previous][node]
        reference_start[node] = math.floor(day_start + busy + idle_before[position])
        busy += service_times[node]
        previous = node


def _generate_time_windows(num_nodes: int, random_seed: int, num_brokers: int, leg_times: list[list[int]],
                           first_legs: list[list[int]], service_times: list[int], horizon: int,
                           fixed_ratio: float, window_width: tuple[int, int],
                           shifts: Optional[list[list[tuple[int, int]]]] = None,
                           lunch_legs: Optional[list[list[int]]] = None,
                           lunch_break: Optional[tuple[int, int, int]] = None,
                           max_day_length: Optional[int] = None) -> dict[str, Any]:
    """
    Builds the time windows around a hidden reference schedule, which guarantees the
    instance is feasible. A share of the visits gets a fixed start time (e_i = l_i),
    emulating visits already scheduled by the visitors.

    Args:
        num_nodes (int): Total number of nodes |V|. Index 0 is the depot.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        num_brokers (int): Number of brokers sharing the hidden schedule.
        leg_times (list[list[int]]): Travel time the hidden schedule takes for each trip, in minutes.
        first_legs (list[list[int]]): Travel time the hidden schedule takes for each broker's
            first trip of the day, to each node, in minutes.
        service_times (list[int]): Duration s_i of the visit at each node, in minutes.
        horizon (int): Target length of the working day, in minutes.
        fixed_ratio (float): Share of the properties with a fixed start time.
        window_width (tuple[int, int]): Min and max width of a flexible time window, in minutes.
        shifts (Optional[list[list[tuple[int, int]]]]): Morning and afternoon shift of each broker.
            When given, the visits of each broker of the hidden schedule fit in his shifts.
        lunch_legs (Optional[list[list[int]]]): Travel time from each broker's lunch spot to each
            node, his first trip of the afternoon shift, in minutes.
        lunch_break (Optional[tuple[int, int, int]]): Earliest start, latest start and duration
            of a lunch break left in each broker's day, when there are no shifts.
        max_day_length (Optional[int]): Longest day of each broker, when there are no shifts.

    Returns:
        dict[str, Any]: The time windows (e_i, l_i) for every node, the fixed visits, and the
            broker who does each visit in the hidden schedule (0 for the depot).

    Raises:
        ValueError: If the shifts are given and the visits don't fit in them, or if some
            broker's visits don't fit in the longest working day.
    """
    num_properties = num_nodes - 1

    # 1. Enforcing Reproducibility
    rng = np.random.default_rng([random_seed, TIME_WINDOWS_STREAM])

    # 2. Hidden Reference Schedule
    # A random visiting order split in consecutive shares among the brokers who work
    reference_order = rng.permutation(np.arange(1, num_nodes))
    working_brokers = [broker for broker in range(1, num_brokers + 1) if shifts is None or shifts[broker - 1]]

    reference_start = [0] * num_nodes
    reference_broker = [0] * num_nodes

    if shifts is None:
        broker_shares = list(zip(working_brokers, np.array_split(reference_order, len(working_brokers))))
        for broker, share in broker_shares:
            for node in share:
                reference_broker[node] = broker

        if max_day_length is not None:
            horizon = min(horizon, max_day_length)

        if lunch_break is None:
            # The day is a target, not a constraint: the models before Case 8 have no working-day
            # limit, so a day too short for the busiest broker's work is extended to fit it
            horizon = max(horizon, max(_workload(share, first_legs[broker - 1], leg_times, service_times)
                                       for broker, share in broker_shares))

            # Each broker's slack in the day is spread as idle gaps between its visits
            for broker, share in broker_shares:
                _place_visits(rng, share, first_legs[broker - 1], leg_times, service_times, 0, horizon,
                              reference_start)
        else:
            # Every broker breaks for lunch inside the lunch window: the first half of his share
            # goes before it, or fewer visits if they don't end by the latest lunch start, and
            # the rest after it, travelling on from his last visit before lunch
            lunch_earliest, lunch_latest, lunch_duration = lunch_break
            lunch_plans = []
            for broker, share in broker_shares:
                first_leg = first_legs[broker - 1]
                split = math.ceil(len(share) / 2)
                while _workload(share[:split], first_leg, leg_times, service_times) > lunch_latest:
                    split -= 1
                morning_workload = _workload(share[:split], first_leg, leg_times, service_times)
                lunch_start = int(rng.integers(max(lunch_earliest, morning_workload), lunch_latest + 1))
                afternoon_leg = leg_times[share[split - 1]] if split else first_leg
                lunch_plans.append((broker, share, split, lunch_start, afternoon_leg))

            horizon = max(horizon, max(lunch_start + lunch_duration
                                       + _workload(share[split:], afternoon_leg, leg_times, service_times)
                                       for _, share, split, lunch_start, afternoon_leg in lunch_plans))

            for broker, share, split, lunch_start, afternoon_leg in lunch_plans:
                _place_visits(rng, share[:split], first_legs[broker - 1], leg_times, service_times,
                              0, lunch_start, reference_start)
                _place_visits(rng, share[split:], afternoon_leg, leg_times, service_times,
                              lunch_start + lunch_duration, horizon, reference_start)

        # Every broker of the hidden schedule leaves at the start of the day and ends by the horizon
        if max_day_length is not None and horizon > max_day_length:
            raise ValueError("Some broker's visits don't fit in the longest working day; "
                             "use more brokers or fewer properties.")
    else:
        horizon = max(horizon, max(end for broker_shifts in shifts for _, end in broker_shifts))

        # The shifts are hard limits, so each shift takes its fair share of the visits left, or
        # fewer if they don't fit, leaving them to the next shifts. The morning shift is done
        # from home and the afternoon one from the lunch spot
        remaining = list(reference_order)
        num_shifts = 2 * len(working_brokers)
        for position in range(num_shifts):
            broker = working_brokers[position // 2]
            shift_start, shift_end = shifts[broker - 1][position % 2]
            first_leg = (first_legs if position % 2 == 0 else lunch_legs)[broker - 1]

            size = math.ceil(len(remaining) / (num_shifts - position))
            while _workload(remaining[:size], first_leg, leg_times, service_times) > shift_end - shift_start:
                size -= 1
            share, remaining = remaining[:size], remaining[size:]

            for node in share:
                reference_broker[node] = broker
            _place_visits(rng, share, first_leg, leg_times, service_times, shift_start, shift_end, reference_start)

        if remaining:
            raise ValueError("The visits don't fit in the brokers' shifts; use more brokers or fewer properties.")

    # 3. Time Windows
    # The depot (node 0) may be left at any time of the day
    earliest_start = [0] * num_nodes
    latest_start = [horizon] * num_nodes

    num_fixed = round(fixed_ratio * num_properties)
    fixed_visits = sorted(int(node) for node in rng.choice(np.arange(1, num_nodes), size=num_fixed, replace=False))

    for node in range(1, num_nodes):
        if node in fixed_visits:
            # Visit already scheduled by the visitor: e_i = l_i
            earliest_start[node] = reference_start[node]
            latest_start[node] = reference_start[node]
        else:
            # Flexible visit: a window containing the reference start time
            width = int(rng.integers(window_width[0], window_width[1] + 1))
            opening = reference_start[node] - int(rng.integers(0, width + 1))
            earliest_start[node] = max(0, opening)
            latest_start[node] = min(horizon - service_times[node], opening + width)

    return {
        'earliest_start': earliest_start,
        'latest_start': latest_start,
        'fixed_visits': fixed_visits,
        'reference_broker': reference_broker
    }


def _generate_assignments(num_nodes: int, random_seed: int, reference_broker: list[int],
                          assigned_ratio: float) -> list[int]:
    """
    Picks the visits that already have a broker, emulating visits booked with a specific
    broker. Each one goes to the broker who does it in the hidden schedule, which keeps
    the instance feasible.

    Args:
        num_nodes (int): Total number of nodes |V|. Index 0 is the depot.
        random_seed (int): Seed for the PRNG to ensure scientific reproducibility.
        reference_broker (list[int]): Broker of each visit in the hidden schedule.
        assigned_ratio (float): Share of the properties whose visit already has a broker.

    Returns:
        list[int]: The broker assigned to each node, 0 when any broker may do it.
    """
    rng = np.random.default_rng([random_seed, ASSIGNMENTS_STREAM])

    num_assigned = round(assigned_ratio * (num_nodes - 1))
    assigned_visits = rng.choice(np.arange(1, num_nodes), size=num_assigned, replace=False)

    assigned_broker = [0] * num_nodes
    for node in assigned_visits:
        assigned_broker[node] = reference_broker[node]

    return assigned_broker


if __name__ == "__main__":
    # Quick sanity check for the terminal
    mock_data = generate_wsrp_instance(num_properties=5)
    print("--- Instance Generation Successful ---")
    print(f"Total Nodes (Depot + Properties): {mock_data['num_nodes']}")
    print("Distance Matrix (0 to 2):")
    for row in mock_data['distance_matrix'][:3]:
        print(row)
    print("Time Windows [e_i, l_i]:")
    for node in range(mock_data['num_nodes']):
        print(f"Node {node}: [{mock_data['earliest_start'][node]}, {mock_data['latest_start'][node]}]")
